import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { lato, montserrat } from "./fonts";
import Social from "./components/Social/Social";
import "react-tooltip/dist/react-tooltip.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.className} ${lato.className}`}>
      <body
        className={`antialiased flex h-screen flex-col lg:flex-row gap-y-4 lg:gap-6 container px-0! items-center lg:py-6`}
      >
        {/* <div className="h-screen overflow-y-hidden"> */}
        <Navbar />
        {/* <div className="w-full lg:h-full"> */}
        <div className="w-full bg-container rounded-2xl p-4 overflow-y-auto h-full overflow-x-hidden">
          {children}
        </div>
        {/* </div> */}
        <Social />
        {/* </div> */}
      </body>
    </html>
  );
}
